name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.14.*'
          terraform_wrapper: false
      - name: Build
        run: |
          go mod download
          make build
          go generate ./...
          git add .
          git diff --staged --exit-code
      - name: Test
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0
